### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by liwenssss** [HKBU-VSComputing/2022_ECCV_NDF#1]
Hi , I run the createDataset.py but got the above problem, can you tell me how to solve it? 
```
File "tools/createDataset.py", line 36, in <listcomp>
    faces.append([int(x.split('/')[0]) for x in strs[1:]])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by liwenssss** [comment]
> Hi , I run the createDataset.py but got the above problem, can you tell me how to solve it?
> 
> ```
> File "tools/createDataset.py", line 36, in <listcomp>
>     faces.append([int(x.split('/')[0]) for x in strs[1:]])
> ValueError: invalid literal for int() with base 10: ''
> ```

Fine , I solved it by add an additional judgemet:
```
faces.append([int(x.split('/')[0]) for x in strs[1:] if len(x) > 0])
UVmap.append([int(x.split('/')[1]) for x in strs[1:] if len(x) > 0])
```

and I evaluate it by run the command 'python run.py --type evaluate --cfg_file configs/zju_mocap_exp/ndf_313.yaml exp_name ndf_313 resume True test_novel_pose False', got the result:
mse: 0.001150000463860896
psnr: 29.92768722194306
ssim: 0.9683096124578988

It seems right. Thanks for your nice work.

**Comment by HelloRicky123** [comment]
Thanks. I will close the issue. Feel free to reopen it with any further problems.
